version: '3.7'
services:
    app:
        container_name: listagem-container
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
        ports:
            - '3001:3000'
        environment:
            - NODE_ENV=development